rundeck-base:
  image: tianon/true
  container_name: rundeck-base
  volumes:
    - /rundeck
tomcat-rundeck:
  extends:
    file: common.yml
    service: tomcat-rundeck
  container_name: rundeck
  environment:
    CATALINA_OPTS: -Xmx1024m -Xms256m -Drdeck.base=/rundeck
  volumes_from:
    - rundeck-base
