tomcat-rundeck:
  extends:
    file: common.yml
    service: tomcat-rundeck
  container_name: rundeck-dev
  environment:
    CATALINA_OPTS: -Xmx1024m -Xms256m -Drdeck.base=/rundeck
  volumes:
    - /rundeck
